/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GrowthStagesRouteImport } from './routes/growth-stages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthStagesRoute = GrowthStagesRouteImport.update({
  id: '/growth-stages',
  path: '/growth-stages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/growth-stages': typeof GrowthStagesRoute
  '/privacy': typeof PrivacyRoute
  '/systems': typeof SystemsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/growth-stages': typeof GrowthStagesRoute
  '/privacy': typeof PrivacyRoute
  '/systems': typeof SystemsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/growth-stages': typeof GrowthStagesRoute
  '/privacy': typeof PrivacyRoute
  '/systems': typeof SystemsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/faq'
    | '/growth-stages'
    | '/privacy'
    | '/systems'
    | '/team'
    | '/terms'
    | '/case-studies/$slug'
    | '/knowledge/$slug'
    | '/solutions/$slug'
    | '/case-studies/'
    | '/knowledge/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/faq'
    | '/growth-stages'
    | '/privacy'
    | '/systems'
    | '/team'
    | '/terms'
    | '/case-studies/$slug'
    | '/knowledge/$slug'
    | '/solutions/$slug'
    | '/case-studies'
    | '/knowledge'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/faq'
    | '/growth-stages'
    | '/privacy'
    | '/systems'
    | '/team'
    | '/terms'
    | '/case-studies/$slug'
    | '/knowledge/$slug'
    | '/solutions/$slug'
    | '/case-studies/'
    | '/knowledge/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GrowthStagesRoute: typeof GrowthStagesRoute
  PrivacyRoute: typeof PrivacyRoute
  SystemsRoute: typeof SystemsRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-stages': {
      id: '/growth-stages'
      path: '/growth-stages'
      fullPath: '/growth-stages'
      preLoaderRoute: typeof GrowthStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GrowthStagesRoute: GrowthStagesRoute,
  PrivacyRoute: PrivacyRoute,
  SystemsRoute: SystemsRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
